In [1]:
import torch


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.4.3 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/opt/homebrew/Caskroom/miniconda/base/envs/data-env/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/data-env/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/data-env/lib/python3.11/site-packages/i

In [3]:
torch.__version__


import cv2
cv2.__version__

'4.13.0'

### 파이토치 기본 
- 텐서(Tensor) : 다차원 배열을 표현하는 자료구조
- 텐서의 종류
    - 스칼라(0차원 텐서)
    - 벡터(1차원 텐서)
    - 행렬(2차원 텐서)
    - 텐서(n차원 텐서) 딥러닝에서 흔히 다루는 데이터 구조


In [7]:
# 텐서 만들기
## 스칼라
x = torch.tensor(5.0)
print(x)
print(x.dim())

tensor(5.)
torch.Size([])
0


In [10]:
# 3차원텐서
y = torch.tensor([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(y)
print(y.dim())

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]])
3


In [11]:
# 텐서 크기
print(y.shape)

torch.Size([2, 2, 3])


In [12]:
# 텐서가 위치한 장치 확인
print(y.device)

cpu


In [13]:
# 모든 원소가 0인 텐서 만들기
zeros = torch.zeros((2,3))
print(zeros)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [14]:
# 모든 원소가 1인 텐서 
t_ones = torch.ones((2,3))
print(t_ones)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [15]:
#0~1사이의 랜덤 값을 가지는 텐서만들기

t_randoms = torch.rand((2,3))
print(t_randoms)


tensor([[0.1053, 0.2450, 0.6598],
        [0.5721, 0.8440, 0.6815]])


### 신경망 핵심원리
- 신경망 개념 
- 신경망 구현순서



#### 문제 
1. 2행 4열의 모든 원소가 9인 텐서를 만드시오
2. 두 텐서 a,b 를 정의하고, 둘의 더한 결과를 출력하시오
    - a -[1,2,3], b -[4,8,10]
3. 텐서 x에서 6과 90만 선택해서 새 텐서 y 를 만드시오
4. 텐서 m과 n의 행렬곱셈 결과를 출력하시오 
    - m: [[1,3], [5,7]], n : [[1,0],[0,1]]




In [16]:
c = torch.ones(2,4)
print(c * 9)


tensor([[9., 9., 9., 9.],
        [9., 9., 9., 9.]])


False
